// Contrato de aquisicao do SynkaCore — FONTE UNICA DE VERDADE.
//
// Deste arquivo e gerado o codigo do gateway (Go), do no em software (Go) e, no
// futuro, do firmware embarcado (nanopb) e do console (TypeScript). Nenhuma das
// pontas escreve o contrato a mao.
//
// DISCIPLINA OBRIGATORIA (o gateway aceita todas as versoes ja publicadas, para
// sempre — nao existe janela de manutencao que alcance 100% da frota):
//
//   1. So ACRESCENTAR campos, e sempre `optional`.
//   2. NUNCA reusar numero de campo. Numero aposentado vira `reserved`.
//   3. NUNCA mudar o tipo de um campo existente.
//   4. NUNCA mudar o significado de um campo existente — semantica nova exige
//      campo novo.
//
// ESTAS REGRAS VALEM A PARTIR DA PRIMEIRA IMPLANTACAO. Enquanto nao houver origem
// em campo, o contrato pode ser reorganizado livremente — e deve ser, porque e a
// ultima janela barata para arruma-lo.
//
// A regra 4 e a que se quebra sem perceber, e a verificacao automatica nao pega:
// `buf breaking` detecta mudanca de tipo e reuso de numero, mas nao detecta que
// alguem decidiu que `valor` agora vem em outra unidade. Essa depende de revisao.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.19.6
// source: synkacore/contrato/v1/aquisicao.proto

package contratov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClasseDeDado classifica o dado pela GARANTIA que ele exige, nao pelo assunto.
//
// Cada classe carrega cinco politicas — entrega, saturacao de buffer, latencia
// maxima, durabilidade local na origem e retencao no gateway. Elas NAO viajam no
// fio: sao derivadas desta anotacao. E isso que impede as duas pontas de
// discordarem sobre o que pode ser descartado — a especie de divergencia que so
// aparece no dia da falha.
type ClasseDeDado int32

const (
	ClasseDeDado_CLASSE_DE_DADO_NAO_ESPECIFICADO ClasseDeDado = 0
	// Telemetria periodica. Tolera perda: a proxima amostra chega logo e carrega
	// quase a mesma informacao.
	ClasseDeDado_CLASSE_DE_DADO_AMOSTRA ClasseDeDado = 1
	// Fato que ocorreu. Nao tolera perda silenciosa: nao tem vizinho que o
	// substitua, e a contagem fica permanentemente errada sem ninguem perceber.
	ClasseDeDado_CLASSE_DE_DADO_EVENTO_DISCRETO ClasseDeDado = 2
)

// Enum value maps for ClasseDeDado.
var (
	ClasseDeDado_name = map[int32]string{
		0: "CLASSE_DE_DADO_NAO_ESPECIFICADO",
		1: "CLASSE_DE_DADO_AMOSTRA",
		2: "CLASSE_DE_DADO_EVENTO_DISCRETO",
	}
	ClasseDeDado_value = map[string]int32{
		"CLASSE_DE_DADO_NAO_ESPECIFICADO": 0,
		"CLASSE_DE_DADO_AMOSTRA":          1,
		"CLASSE_DE_DADO_EVENTO_DISCRETO":  2,
	}
)

func (x ClasseDeDado) Enum() *ClasseDeDado {
	p := new(ClasseDeDado)
	*p = x
	return p
}

func (x ClasseDeDado) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClasseDeDado) Descriptor() protoreflect.EnumDescriptor {
	return file_synkacore_contrato_v1_aquisicao_proto_enumTypes[0].Descriptor()
}

func (ClasseDeDado) Type() protoreflect.EnumType {
	return &file_synkacore_contrato_v1_aquisicao_proto_enumTypes[0]
}

func (x ClasseDeDado) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClasseDeDado.Descriptor instead.
func (ClasseDeDado) EnumDescriptor() ([]byte, []int) {
	return file_synkacore_contrato_v1_aquisicao_proto_rawDescGZIP(), []int{0}
}

// EstadoDeMaquina declara o estado OBSERVADO. NAO declara como ele afeta a
// disponibilidade — isso e regra de negocio, vive no gateway e e configuravel por
// planta, porque plantas discordam legitimamente (algumas descontam setup do
// tempo programado, outras nao). Codificar a politica no contrato obrigaria mudar
// o contrato para atender um cliente, que e a coisa mais cara de mudar.
type EstadoDeMaquina int32

const (
	EstadoDeMaquina_ESTADO_DE_MAQUINA_NAO_ESPECIFICADO EstadoDeMaquina = 0
	EstadoDeMaquina_ESTADO_DE_MAQUINA_RODANDO          EstadoDeMaquina = 1
	// Parada sem classificacao ainda. Legitimo: o operador pode nao ter
	// classificado, e forcar uma classificacao errada e pior que admitir a falta.
	EstadoDeMaquina_ESTADO_DE_MAQUINA_PARADA EstadoDeMaquina = 2
	// Troca de ferramenta ou preparacao. Parada planejada.
	EstadoDeMaquina_ESTADO_DE_MAQUINA_SETUP EstadoDeMaquina = 3
	// Maquina saudavel e parada por falta de insumo ou de operador. Separado de
	// quebra porque e problema de logistica, nao de manutencao — juntos, o
	// indicador culpa a maquina errada.
	EstadoDeMaquina_ESTADO_DE_MAQUINA_OCIOSA EstadoDeMaquina = 4
	// Manutencao preventiva programada. Separado de quebra porque, somados, toda
	// preventiva bem-feita piora o indicador — e ai ninguem quer fazer preventiva.
	EstadoDeMaquina_ESTADO_DE_MAQUINA_MANUTENCAO_PROGRAMADA EstadoDeMaquina = 5
	// Falha nao planejada. E a base do tempo medio entre falhas, e portanto da
	// manutencao preditiva.
	EstadoDeMaquina_ESTADO_DE_MAQUINA_QUEBRA EstadoDeMaquina = 6
)

// Enum value maps for EstadoDeMaquina.
var (
	EstadoDeMaquina_name = map[int32]string{
		0: "ESTADO_DE_MAQUINA_NAO_ESPECIFICADO",
		1: "ESTADO_DE_MAQUINA_RODANDO",
		2: "ESTADO_DE_MAQUINA_PARADA",
		3: "ESTADO_DE_MAQUINA_SETUP",
		4: "ESTADO_DE_MAQUINA_OCIOSA",
		5: "ESTADO_DE_MAQUINA_MANUTENCAO_PROGRAMADA",
		6: "ESTADO_DE_MAQUINA_QUEBRA",
	}
	EstadoDeMaquina_value = map[string]int32{
		"ESTADO_DE_MAQUINA_NAO_ESPECIFICADO":      0,
		"ESTADO_DE_MAQUINA_RODANDO":               1,
		"ESTADO_DE_MAQUINA_PARADA":                2,
		"ESTADO_DE_MAQUINA_SETUP":                 3,
		"ESTADO_DE_MAQUINA_OCIOSA":                4,
		"ESTADO_DE_MAQUINA_MANUTENCAO_PROGRAMADA": 5,
		"ESTADO_DE_MAQUINA_QUEBRA":                6,
	}
)

func (x EstadoDeMaquina) Enum() *EstadoDeMaquina {
	p := new(EstadoDeMaquina)
	*p = x
	return p
}

func (x EstadoDeMaquina) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EstadoDeMaquina) Descriptor() protoreflect.EnumDescriptor {
	return file_synkacore_contrato_v1_aquisicao_proto_enumTypes[1].Descriptor()
}

func (EstadoDeMaquina) Type() protoreflect.EnumType {
	return &file_synkacore_contrato_v1_aquisicao_proto_enumTypes[1]
}

func (x EstadoDeMaquina) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EstadoDeMaquina.Descriptor instead.
func (EstadoDeMaquina) EnumDescriptor() ([]byte, []int) {
	return file_synkacore_contrato_v1_aquisicao_proto_rawDescGZIP(), []int{1}
}

type Grandeza int32

const (
	Grandeza_GRANDEZA_NAO_ESPECIFICADO       Grandeza = 0
	Grandeza_GRANDEZA_TEMPERATURA            Grandeza = 1
	Grandeza_GRANDEZA_PRESSAO                Grandeza = 2
	Grandeza_GRANDEZA_UMIDADE_DO_AR          Grandeza = 3
	Grandeza_GRANDEZA_VAZAO                  Grandeza = 4
	Grandeza_GRANDEZA_MASSA                  Grandeza = 5
	Grandeza_GRANDEZA_NIVEL                  Grandeza = 6
	Grandeza_GRANDEZA_CORRENTE_ELETRICA      Grandeza = 7
	Grandeza_GRANDEZA_ACELERACAO_DE_VIBRACAO Grandeza = 8
	Grandeza_GRANDEZA_ESTADO_DIGITAL         Grandeza = 9
	Grandeza_GRANDEZA_CONTAGEM_DE_PECAS      Grandeza = 10
	// Qualidade de produto — agroindustria.
	Grandeza_GRANDEZA_PH                     Grandeza = 11
	Grandeza_GRANDEZA_CONDUTIVIDADE_ELETRICA Grandeza = 12
	// Umidade do MATERIAL, distinta de GRANDEZA_UMIDADE_DO_AR, que e do ar. Sao
	// grandezas diferentes e confundi-las inutiliza o dado de secagem.
	Grandeza_GRANDEZA_UMIDADE_DE_GRAO Grandeza = 13
	Grandeza_GRANDEZA_BRIX            Grandeza = 14
	// Mecanicas.
	//
	// Rotacao costuma ser indispensavel junto de vibracao: amplitude de vibracao
	// sem a rotacao correspondente e quase ininterpretavel, porque a assinatura
	// esperada muda com a velocidade.
	Grandeza_GRANDEZA_ROTACAO           Grandeza = 15
	Grandeza_GRANDEZA_TORQUE            Grandeza = 16
	Grandeza_GRANDEZA_VELOCIDADE_LINEAR Grandeza = 17
	// Eletricas.
	Grandeza_GRANDEZA_TENSAO         Grandeza = 18
	Grandeza_GRANDEZA_POTENCIA_ATIVA Grandeza = 19
	// Energia acumulada usa LeituraDeContador, nunca AmostraEscalar: e um
	// acumulador monotonico, e leitura acumulada perdida se recupera sozinha.
	Grandeza_GRANDEZA_ENERGIA_ELETRICA Grandeza = 20
)

// Enum value maps for Grandeza.
var (
	Grandeza_name = map[int32]string{
		0:  "GRANDEZA_NAO_ESPECIFICADO",
		1:  "GRANDEZA_TEMPERATURA",
		2:  "GRANDEZA_PRESSAO",
		3:  "GRANDEZA_UMIDADE_DO_AR",
		4:  "GRANDEZA_VAZAO",
		5:  "GRANDEZA_MASSA",
		6:  "GRANDEZA_NIVEL",
		7:  "GRANDEZA_CORRENTE_ELETRICA",
		8:  "GRANDEZA_ACELERACAO_DE_VIBRACAO",
		9:  "GRANDEZA_ESTADO_DIGITAL",
		10: "GRANDEZA_CONTAGEM_DE_PECAS",
		11: "GRANDEZA_PH",
		12: "GRANDEZA_CONDUTIVIDADE_ELETRICA",
		13: "GRANDEZA_UMIDADE_DE_GRAO",
		14: "GRANDEZA_BRIX",
		15: "GRANDEZA_ROTACAO",
		16: "GRANDEZA_TORQUE",
		17: "GRANDEZA_VELOCIDADE_LINEAR",
		18: "GRANDEZA_TENSAO",
		19: "GRANDEZA_POTENCIA_ATIVA",
		20: "GRANDEZA_ENERGIA_ELETRICA",
	}
	Grandeza_value = map[string]int32{
		"GRANDEZA_NAO_ESPECIFICADO":       0,
		"GRANDEZA_TEMPERATURA":            1,
		"GRANDEZA_PRESSAO":                2,
		"GRANDEZA_UMIDADE_DO_AR":          3,
		"GRANDEZA_VAZAO":                  4,
		"GRANDEZA_MASSA":                  5,
		"GRANDEZA_NIVEL":                  6,
		"GRANDEZA_CORRENTE_ELETRICA":      7,
		"GRANDEZA_ACELERACAO_DE_VIBRACAO": 8,
		"GRANDEZA_ESTADO_DIGITAL":         9,
		"GRANDEZA_CONTAGEM_DE_PECAS":      10,
		"GRANDEZA_PH":                     11,
		"GRANDEZA_CONDUTIVIDADE_ELETRICA": 12,
		"GRANDEZA_UMIDADE_DE_GRAO":        13,
		"GRANDEZA_BRIX":                   14,
		"GRANDEZA_ROTACAO":                15,
		"GRANDEZA_TORQUE":                 16,
		"GRANDEZA_VELOCIDADE_LINEAR":      17,
		"GRANDEZA_TENSAO":                 18,
		"GRANDEZA_POTENCIA_ATIVA":         19,
		"GRANDEZA_ENERGIA_ELETRICA":       20,
	}
)

func (x Grandeza) Enum() *Grandeza {
	p := new(Grandeza)
	*p = x
	return p
}

func (x Grandeza) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Grandeza) Descriptor() protoreflect.EnumDescriptor {
	return file_synkacore_contrato_v1_aquisicao_proto_enumTypes[2].Descriptor()
}

func (Grandeza) Type() protoreflect.EnumType {
	return &file_synkacore_contrato_v1_aquisicao_proto_enumTypes[2]
}

func (x Grandeza) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Grandeza.Descriptor instead.
func (Grandeza) EnumDescriptor() ([]byte, []int) {
	return file_synkacore_contrato_v1_aquisicao_proto_rawDescGZIP(), []int{2}
}

// Remessa e o lote: tudo que uma origem envia de uma vez.
//
// O lote nao e otimizacao, e pre-requisito de viabilidade: sem ele, o fsync
// sozinho consumiria toda a capacidade do disco do gateway no cenario
// dimensionado, e uma requisicao HTTPS por amostra seria inviavel numa origem
// embarcada.
//
// Uma remessa pertence a UMA origem e UMA sessao de boot. Isso permite que a
// confirmacao seja uma faixa de numeros de sequencia em vez de uma lista.
type Remessa struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Versao do contrato que esta origem fala.
	//
	// NAO e portao de compatibilidade. E observabilidade de frota: responde "quais
	// origens ainda nao foram atualizadas?" sem ir a campo conferir.
	VersaoDoEsquema *uint32 `protobuf:"varint,1,opt,name=versao_do_esquema,json=versaoDoEsquema,proto3,oneof" json:"versao_do_esquema,omitempty"`
	// Instalacao. Necessario porque o produto e replicado em varias plantas e uma
	// planta pode ter varios gateways.
	IdDaInstalacao *string `protobuf:"bytes,2,opt,name=id_da_instalacao,json=idDaInstalacao,proto3,oneof" json:"id_da_instalacao,omitempty"`
	// Identidade REIVINDICADA pela origem.
	//
	// O gateway compara com a identidade que o transporte provou (mTLS) e recusa
	// divergencia. Sem essa conferencia, uma origem legitima poderia enviar dados
	// se passando por outra.
	//
	// Unico na instalacao inteira, nunca apenas dentro de um gateway.
	IdDoDispositivo *string `protobuf:"bytes,3,opt,name=id_do_dispositivo,json=idDoDispositivo,proto3,oneof" json:"id_do_dispositivo,omitempty"`
	// Sessao de boot: sorteada a cada partida da origem.
	//
	// Uma origem embarcada nao tem relogio de tempo real com bateria — ao ligar,
	// seu relogio comeca em 1970. Ela NUNCA afirma saber a hora. Este identificador
	// e o que permite ao gateway ancorar o tempo monotonico da origem ao seu
	// proprio relogio, e e o que impede os numeros de sequencia de colidirem entre
	// partidas.
	IdDaSessaoDeBoot *string     `protobuf:"bytes,4,opt,name=id_da_sessao_de_boot,json=idDaSessaoDeBoot,proto3,oneof" json:"id_da_sessao_de_boot,omitempty"`
	Envelopes        []*Envelope `protobuf:"bytes,5,rep,name=envelopes,proto3" json:"envelopes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Remessa) Reset() {
	*x = Remessa{}
	mi := &file_synkacore_contrato_v1_aquisicao_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Remessa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Remessa) ProtoMessage() {}

func (x *Remessa) ProtoReflect() protoreflect.Message {
	mi := &file_synkacore_contrato_v1_aquisicao_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Remessa.ProtoReflect.Descriptor instead.
func (*Remessa) Descriptor() ([]byte, []int) {
	return file_synkacore_contrato_v1_aquisicao_proto_rawDescGZIP(), []int{0}
}

func (x *Remessa) GetVersaoDoEsquema() uint32 {
	if x != nil && x.VersaoDoEsquema != nil {
		return *x.VersaoDoEsquema
	}
	return 0
}

func (x *Remessa) GetIdDaInstalacao() string {
	if x != nil && x.IdDaInstalacao != nil {
		return *x.IdDaInstalacao
	}
	return ""
}

func (x *Remessa) GetIdDoDispositivo() string {
	if x != nil && x.IdDoDispositivo != nil {
		return *x.IdDoDispositivo
	}
	return ""
}

func (x *Remessa) GetIdDaSessaoDeBoot() string {
	if x != nil && x.IdDaSessaoDeBoot != nil {
		return *x.IdDaSessaoDeBoot
	}
	return ""
}

func (x *Remessa) GetEnvelopes() []*Envelope {
	if x != nil {
		return x.Envelopes
	}
	return nil
}

// Envelope e uma mensagem dentro da remessa.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unico dentro da sessao de boot. Compoe a chave de idempotencia junto com
	// id_do_dispositivo e id_da_sessao_de_boot, e permite ao gateway detectar
	// lacuna em transito.
	NumeroDeSequencia *uint64 `protobuf:"varint,1,opt,name=numero_de_sequencia,json=numeroDeSequencia,proto3,oneof" json:"numero_de_sequencia,omitempty"`
	// Tempo MONOTONICO desde o boot da origem. E o unico tempo que ela tem
	// autoridade para afirmar. O gateway carimba a recepcao e deriva o instante
	// estimado; o derivado nunca sobrescreve este valor.
	TempoLigadoMs *uint64 `protobuf:"varint,2,opt,name=tempo_ligado_ms,json=tempoLigadoMs,proto3,oneof" json:"tempo_ligado_ms,omitempty"`
	// Numeros 3 a 10 tem tag de 1 byte e ficam reservados aos conteudos frequentes.
	//
	// Types that are valid to be assigned to Conteudo:
	//
	//	*Envelope_AmostraEscalar
	//	*Envelope_LeituraDeContador
	//	*Envelope_TransicaoDigital
	//	*Envelope_AmostraAgregada
	//	*Envelope_MudancaDeEstadoDeMaquina
	//	*Envelope_SaudeDaOrigem
	//	*Envelope_LacunaDeBuffer
	//	*Envelope_DescritorDaOrigem
	Conteudo      isEnvelope_Conteudo `protobuf_oneof:"conteudo"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_synkacore_contrato_v1_aquisicao_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_synkacore_contrato_v1_aquisicao_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_synkacore_contrato_v1_aquisicao_proto_rawDescGZIP(), []int{1}
}

func (x *Envelope) GetNumeroDeSequencia() uint64 {
	if x != nil && x.NumeroDeSequencia != nil {
		return *x.NumeroDeSequencia
	}
	return 0
}

func (x *Envelope) GetTempoLigadoMs() uint64 {
	if x != nil && x.TempoLigadoMs != nil {
		return *x.TempoLigadoMs
	}
	return 0
}

func (x *Envelope) GetConteudo() isEnvelope_Conteudo {
	if x != nil {
		return x.Conteudo
	}
	return nil
}

func (x *Envelope) GetAmostraEscalar() *AmostraEscalar {
	if x != nil {
		if x, ok := x.Conteudo.(*Envelope_AmostraEscalar); ok {
			return x.AmostraEscalar
		}
	}
	return nil
}

func (x *Envelope) GetLeituraDeContador() *LeituraDeContador {
	if x != nil {
		if x, ok := x.Conteudo.(*Envelope_LeituraDeContador); ok {
			return x.LeituraDeContador
		}
	}
	return nil
}

func (x *Envelope) GetTransicaoDigital() *TransicaoDigital {
	if x != nil {
		if x, ok := x.Conteudo.(*Envelope_TransicaoDigital); ok {
			return x.TransicaoDigital
		}
	}
	return nil
}

func (x *Envelope) GetAmostraAgregada() *AmostraAgregada {
	if x != nil {
		if x, ok := x.Conteudo.(*Envelope_AmostraAgregada); ok {
			return x.AmostraAgregada
		}
	}
	return nil
}

func (x *Envelope) GetMudancaDeEstadoDeMaquina() *MudancaDeEstadoDeMaquina {
	if x != nil {
		if x, ok := x.Conteudo.(*Envelope_MudancaDeEstadoDeMaquina); ok {
			return x.MudancaDeEstadoDeMaquina
		}
	}
	return nil
}

func (x *Envelope) GetSaudeDaOrigem() *SaudeDaOrigem {
	if x != nil {
		if x, ok := x.Conteudo.(*Envelope_SaudeDaOrigem); ok {
			return x.SaudeDaOrigem
		}
	}
	return nil
}

func (x *Envelope) GetLacunaDeBuffer() *LacunaDeBuffer {
	if x != nil {
		if x, ok := x.Conteudo.(*Envelope_LacunaDeBuffer); ok {
			return x.LacunaDeBuffer
		}
	}
	return nil
}

func (x *Envelope) GetDescritorDaOrigem() *DescritorDaOrigem {
	if x != nil {
		if x, ok := x.Conteudo.(*Envelope_DescritorDaOrigem); ok {
			return x.DescritorDaOrigem
		}
	}
	return nil
}

type isEnvelope_Conteudo interface {
	isEnvelope_Conteudo()
}

type Envelope_AmostraEscalar struct {
	AmostraEscalar *AmostraEscalar `protobuf:"bytes,3,opt,name=amostra_escalar,json=amostraEscalar,proto3,oneof"`
}

type Envelope_LeituraDeContador struct {
	LeituraDeContador *LeituraDeContador `protobuf:"bytes,4,opt,name=leitura_de_contador,json=leituraDeContador,proto3,oneof"`
}

type Envelope_TransicaoDigital struct {
	TransicaoDigital *TransicaoDigital `protobuf:"bytes,5,opt,name=transicao_digital,json=transicaoDigital,proto3,oneof"`
}

type Envelope_AmostraAgregada struct {
	AmostraAgregada *AmostraAgregada `protobuf:"bytes,6,opt,name=amostra_agregada,json=amostraAgregada,proto3,oneof"`
}

type Envelope_MudancaDeEstadoDeMaquina struct {
	MudancaDeEstadoDeMaquina *MudancaDeEstadoDeMaquina `protobuf:"bytes,7,opt,name=mudanca_de_estado_de_maquina,json=mudancaDeEstadoDeMaquina,proto3,oneof"`
}

type Envelope_SaudeDaOrigem struct {
	SaudeDaOrigem *SaudeDaOrigem `protobuf:"bytes,8,opt,name=saude_da_origem,json=saudeDaOrigem,proto3,oneof"`
}

type Envelope_LacunaDeBuffer struct {
	LacunaDeBuffer *LacunaDeBuffer `protobuf:"bytes,9,opt,name=lacuna_de_buffer,json=lacunaDeBuffer,proto3,oneof"`
}

type Envelope_DescritorDaOrigem struct {
	DescritorDaOrigem *DescritorDaOrigem `protobuf:"bytes,10,opt,name=descritor_da_origem,json=descritorDaOrigem,proto3,oneof"`
}

func (*Envelope_AmostraEscalar) isEnvelope_Conteudo() {}

func (*Envelope_LeituraDeContador) isEnvelope_Conteudo() {}

func (*Envelope_TransicaoDigital) isEnvelope_Conteudo() {}

func (*Envelope_AmostraAgregada) isEnvelope_Conteudo() {}

func (*Envelope_MudancaDeEstadoDeMaquina) isEnvelope_Conteudo() {}

func (*Envelope_SaudeDaOrigem) isEnvelope_Conteudo() {}

func (*Envelope_LacunaDeBuffer) isEnvelope_Conteudo() {}

func (*Envelope_DescritorDaOrigem) isEnvelope_Conteudo() {}

// ConfirmacaoDeRemessa e a resposta do gateway.
type ConfirmacaoDeRemessa struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tudo ate este numero, inclusive, esta DURAVEL no diario. A origem pode
	// liberar o buffer ate aqui.
	//
	// Faixa contigua em vez de lista porque a remessa e de uma so origem e uma so
	// sessao: os numeros sao contiguos por construcao. Duplicatas contam como
	// sucesso — reentrega e consequencia esperada de entrega ao-menos-uma-vez, nao
	// anomalia.
	DuravelAteASequencia *uint64 `protobuf:"varint,1,opt,name=duravel_ate_a_sequencia,json=duravelAteASequencia,proto3,oneof" json:"duravel_ate_a_sequencia,omitempty"`
	// Rejeitados por conteudo invalido. Retransmitir NAO adianta, e a origem deve
	// descarta-los em vez de tentar para sempre.
	SequenciasRejeitadasDefinitivamente []uint64 `protobuf:"varint,2,rep,packed,name=sequencias_rejeitadas_definitivamente,json=sequenciasRejeitadasDefinitivamente,proto3" json:"sequencias_rejeitadas_definitivamente,omitempty"`
	// Contrapressao: quanto esperar antes da proxima remessa.
	//
	// A origem soma jitter aleatorio a este valor. Sem jitter, as origens
	// sincronizam e a frota inteira reconecta junto — a falha parcial vira total,
	// que e o modo de falha que derruba o gateway que estava apenas lento.
	RepetirAposMs *uint32 `protobuf:"varint,3,opt,name=repetir_apos_ms,json=repetirAposMs,proto3,oneof" json:"repetir_apos_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmacaoDeRemessa) Reset() {
	*x = ConfirmacaoDeRemessa{}
	mi := &file_synkacore_contrato_v1_aquisicao_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmacaoDeRemessa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmacaoDeRemessa) ProtoMessage() {}

func (x *ConfirmacaoDeRemessa) ProtoReflect() protoreflect.Message {
	mi := &file_synkacore_contrato_v1_aquisicao_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmacaoDeRemessa.ProtoReflect.Descriptor instead.
func (*ConfirmacaoDeRemessa) Descriptor() ([]byte, []int) {
	return file_synkacore_contrato_v1_aquisicao_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmacaoDeRemessa) GetDuravelAteASequencia() uint64 {
	if x != nil && x.DuravelAteASequencia != nil {
		return *x.DuravelAteASequencia
	}
	return 0
}

func (x *ConfirmacaoDeRemessa) GetSequenciasRejeitadasDefinitivamente() []uint64 {
	if x != nil {
		return x.SequenciasRejeitadasDefinitivamente
	}
	return nil
}

func (x *ConfirmacaoDeRemessa) GetRepetirAposMs() uint32 {
	if x != nil && x.RepetirAposMs != nil {
		return *x.RepetirAposMs
	}
	return 0
}

// EnderecoDeCanal localiza uma entrada fisica dentro de uma origem.
//
// Extraido em mensagem propria, e nao repetido como dois campos soltos em cada
// conteudo, por uma razao de codigo gerado e nao de bytes: assim a funcao que
// resolve endereco para ponto de medicao recebe UM argumento tipado, e ninguem
// consegue trocar a ordem de modulo e canal numa chamada. Dois uint32 adjacentes
// numa assinatura sao uma armadilha silenciosa — compila, roda, e atribui a
// leitura ao ponto errado.
type EnderecoDeCanal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Placa de expansao ou escravo no barramento. Zero e a propria origem.
	//
	// Existe porque a alternativa seria convencionar faixas de indice ("modulo 1 =
	// canais 100-199"), e convencao nao e garantia: o dia em que alguem passar de
	// 199 canais, o dado fica errado sem nenhum erro.
	IndiceDoModulo *uint32 `protobuf:"varint,1,opt,name=indice_do_modulo,json=indiceDoModulo,proto3,oneof" json:"indice_do_modulo,omitempty"`
	// Entrada dentro do modulo.
	IndiceDoCanal *uint32 `protobuf:"varint,2,opt,name=indice_do_canal,json=indiceDoCanal,proto3,oneof" json:"indice_do_canal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnderecoDeCanal) Reset() {
	*x = EnderecoDeCanal{}
	mi := &file_synkacore_contrato_v1_aquisicao_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnderecoDeCanal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnderecoDeCanal) ProtoMessage() {}

func (x *EnderecoDeCanal) ProtoReflect() protoreflect.Message {
	mi := &file_synkacore_contrato_v1_aquisicao_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnderecoDeCanal.ProtoReflect.Descriptor instead.
func (*EnderecoDeCanal) Descriptor() ([]byte, []int) {
	return file_synkacore_contrato_v1_aquisicao_proto_rawDescGZIP(), []int{3}
}

func (x *EnderecoDeCanal) GetIndiceDoModulo() uint32 {
	if x != nil && x.IndiceDoModulo != nil {
		return *x.IndiceDoModulo
	}
	return 0
}

func (x *EnderecoDeCanal) GetIndiceDoCanal() uint32 {
	if x != nil && x.IndiceDoCanal != nil {
		return *x.IndiceDoCanal
	}
	return 0
}

// AmostraEscalar e o valor de uma grandeza continua num instante.
//
// DECISAO IMPORTANTE: existe UM tipo para todas as grandezas escalares —
// temperatura, pressao, umidade, vazao, peso, nivel, corrente.
//
// Tipos separados seriam estruturas IDENTICAS com nomes diferentes: exatamente a
// duplicacao que o projeto proibe. A diferenca entre elas nao e estrutural, e
// semantica — e semantica e configuracao do ponto de medicao, nao formato de
// mensagem.
//
// A origem reporta o CANAL. O gateway resolve canal para ponto de medicao, e dai
// para grandeza, unidade e faixa valida. A origem continua burra; o gateway deriva.
type AmostraEscalar struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Endereco *EnderecoDeCanal       `protobuf:"bytes,1,opt,name=endereco,proto3,oneof" json:"endereco,omitempty"`
	// Valor na unidade declarada pelo DescritorDaOrigem do canal.
	//
	// `float` e nao `double` de proposito: conversores analogico-digitais
	// industriais tem 12 a 16 bits, e float32 carrega ~7 digitos significativos —
	// folgado. `double` dobraria os bytes no fio sem acrescentar informacao real.
	Valor         *float32 `protobuf:"fixed32,2,opt,name=valor,proto3,oneof" json:"valor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AmostraEscalar) Reset() {
	*x = AmostraEscalar{}
	mi := &file_synkacore_contrato_v1_aquisicao_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AmostraEscalar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmostraEscalar) ProtoMessage() {}

func (x *AmostraEscalar) ProtoReflect() protoreflect.Message {
	mi := &file_synkacore_contrato_v1_aquisicao_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmostraEscalar.ProtoReflect.Descriptor instead.
func (*AmostraEscalar) Descriptor() ([]byte, []int) {
	return file_synkacore_contrato_v1_aquisicao_proto_rawDescGZIP(), []int{4}
}

func (x *AmostraEscalar) GetEndereco() *EnderecoDeCanal {
	if x != nil {
		return x.Endereco
	}
	return nil
}

func (x *AmostraEscalar) GetValor() float32 {
	if x != nil && x.Valor != nil {
		return *x.Valor
	}
	return 0
}

// AmostraAgregada resume muitas amostras colhidas rapido demais para trafegar.
//
// Razao de existir: vibracao e corrente exigem centenas a milhares de amostras
// por segundo. Esse sinal nao pode ir bruto.
//
// A origem calcula os indicadores sobre uma janela. Isso e CONDICIONAMENTO DE
// SINAL, nao regra de negocio: e o equivalente digital do que um transdutor
// analogico ja faria em hardware. Decidir que "valor eficaz acima de 5 e alarme"
// continua proibido na origem — ela nao decide, apenas mede.
//
// Sem os campos de janela e contagem, um valor eficaz de 1024 amostras chegaria
// indistinguivel de uma leitura unica, e qualquer estatistica posterior estaria
// errada sem aviso.
type AmostraAgregada struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Endereco *EnderecoDeCanal       `protobuf:"bytes,1,opt,name=endereco,proto3,oneof" json:"endereco,omitempty"`
	// Duracao da janela agregada. O tempo ligado do Envelope marca o FIM da janela.
	JanelaMs *uint32 `protobuf:"varint,2,opt,name=janela_ms,json=janelaMs,proto3,oneof" json:"janela_ms,omitempty"`
	// Quantas amostras brutas entraram. Necessario para reagregar corretamente ao
	// consolidar janelas no gateway — media de medias sem peso e errada.
	QuantidadeDeAmostras *uint32  `protobuf:"varint,3,opt,name=quantidade_de_amostras,json=quantidadeDeAmostras,proto3,oneof" json:"quantidade_de_amostras,omitempty"`
	Minimo               *float32 `protobuf:"fixed32,4,opt,name=minimo,proto3,oneof" json:"minimo,omitempty"`
	Maximo               *float32 `protobuf:"fixed32,5,opt,name=maximo,proto3,oneof" json:"maximo,omitempty"`
	Media                *float32 `protobuf:"fixed32,6,opt,name=media,proto3,oneof" json:"media,omitempty"`
	// Valor eficaz. E o indicador que importa em vibracao e corrente alternada,
	// onde a media tende a zero e nao diz nada.
	ValorEficaz   *float32 `protobuf:"fixed32,7,opt,name=valor_eficaz,json=valorEficaz,proto3,oneof" json:"valor_eficaz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AmostraAgregada) Reset() {
	*x = AmostraAgregada{}
	mi := &file_synkacore_contrato_v1_aquisicao_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AmostraAgregada) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmostraAgregada) ProtoMessage() {}

func (x *AmostraAgregada) ProtoReflect() protoreflect.Message {
	mi := &file_synkacore_contrato_v1_aquisicao_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmostraAgregada.ProtoReflect.Descriptor instead.
func (*AmostraAgregada) Descriptor() ([]byte, []int) {
	return file_synkacore_contrato_v1_aquisicao_proto_rawDescGZIP(), []int{5}
}

func (x *AmostraAgregada) GetEndereco() *EnderecoDeCanal {
	if x != nil {
		return x.Endereco
	}
	return nil
}

func (x *AmostraAgregada) GetJanelaMs() uint32 {
	if x != nil && x.JanelaMs != nil {
		return *x.JanelaMs
	}
	return 0
}

func (x *AmostraAgregada) GetQuantidadeDeAmostras() uint32 {
	if x != nil && x.QuantidadeDeAmostras != nil {
		return *x.QuantidadeDeAmostras
	}
	return 0
}

func (x *AmostraAgregada) GetMinimo() float32 {
	if x != nil && x.Minimo != nil {
		return *x.Minimo
	}
	return 0
}

func (x *AmostraAgregada) GetMaximo() float32 {
	if x != nil && x.Maximo != nil {
		return *x.Maximo
	}
	return 0
}

func (x *AmostraAgregada) GetMedia() float32 {
	if x != nil && x.Media != nil {
		return *x.Media
	}
	return 0
}

func (x *AmostraAgregada) GetValorEficaz() float32 {
	if x != nil && x.ValorEficaz != nil {
		return *x.ValorEficaz
	}
	return 0
}

// LeituraDeContador e a contagem ACUMULADA de um canal na sessao de boot.
//
// DECISAO IMPORTANTE: acumulada, nunca incremental.
//
// Um incremento perdido some para sempre e a contagem fica permanentemente
// errada. Uma leitura acumulada perdida e recuperada pela proxima: a perda se
// cura sozinha. Como contagem de producao e numero que o gestor usa para decidir,
// essa diferenca separa um relatorio confiavel de um plausivel.
type LeituraDeContador struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Endereco *EnderecoDeCanal       `protobuf:"bytes,1,opt,name=endereco,proto3,oneof" json:"endereco,omitempty"`
	// Contagem acumulada em UNIDADE INTEIRA, declarada no DescritorDeCanal.
	//
	// Inteiro e nao ponto flutuante de proposito: acumulador em float acumula erro
	// de arredondamento indefinidamente, e o erro cresce justamente quando o numero
	// fica grande — que e quando alguem vai olhar. Energia usa Wh, nao kWh; volume
	// usa mL, nao L. A conversao para a unidade de exibicao e do gateway.
	ContagemAcumulada *uint64 `protobuf:"varint,2,opt,name=contagem_acumulada,json=contagemAcumulada,proto3,oneof" json:"contagem_acumulada,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LeituraDeContador) Reset() {
	*x = LeituraDeContador{}
	mi := &file_synkacore_contrato_v1_aquisicao_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeituraDeContador) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeituraDeContador) ProtoMessage() {}

func (x *LeituraDeContador) ProtoReflect() protoreflect.Message {
	mi := &file_synkacore_contrato_v1_aquisicao_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeituraDeContador.ProtoReflect.Descriptor instead.
func (*LeituraDeContador) Descriptor() ([]byte, []int) {
	return file_synkacore_contrato_v1_aquisicao_proto_rawDescGZIP(), []int{6}
}

func (x *LeituraDeContador) GetEndereco() *EnderecoDeCanal {
	if x != nil {
		return x.Endereco
	}
	return nil
}

func (x *LeituraDeContador) GetContagemAcumulada() uint64 {
	if x != nil && x.ContagemAcumulada != nil {
		return *x.ContagemAcumulada
	}
	return 0
}

// TransicaoDigital registra a mudanca de estado de uma entrada discreta.
type TransicaoDigital struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endereco      *EnderecoDeCanal       `protobuf:"bytes,1,opt,name=endereco,proto3,oneof" json:"endereco,omitempty"`
	Ativo         *bool                  `protobuf:"varint,2,opt,name=ativo,proto3,oneof" json:"ativo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransicaoDigital) Reset() {
	*x = TransicaoDigital{}
	mi := &file_synkacore_contrato_v1_aquisicao_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransicaoDigital) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransicaoDigital) ProtoMessage() {}

func (x *TransicaoDigital) ProtoReflect() protoreflect.Message {
	mi := &file_synkacore_contrato_v1_aquisicao_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransicaoDigital.ProtoReflect.Descriptor instead.
func (*TransicaoDigital) Descriptor() ([]byte, []int) {
	return file_synkacore_contrato_v1_aquisicao_proto_rawDescGZIP(), []int{7}
}

func (x *TransicaoDigital) GetEndereco() *EnderecoDeCanal {
	if x != nil {
		return x.Endereco
	}
	return nil
}

func (x *TransicaoDigital) GetAtivo() bool {
	if x != nil && x.Ativo != nil {
		return *x.Ativo
	}
	return false
}

// MudancaDeEstadoDeMaquina registra a transicao de estado operacional.
type MudancaDeEstadoDeMaquina struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Endereco *EnderecoDeCanal       `protobuf:"bytes,1,opt,name=endereco,proto3,oneof" json:"endereco,omitempty"`
	Estado   *EstadoDeMaquina       `protobuf:"varint,2,opt,name=estado,proto3,enum=synkacore.contrato.v1.EstadoDeMaquina,oneof" json:"estado,omitempty"`
	// Motivo apontado na interface do operador, como CODIGO do catalogo da instalacao.
	//
	// Inteiro e nao texto livre: texto livre produz "quebra", "Quebra" e "quebrou"
	// como motivos distintos, e o relatorio agrupa errado sem ninguem perceber. O
	// gateway recusa codigo fora do catalogo, entao o dado nasce consistente.
	//
	// Ausente significa parada ainda nao classificada — informacao legitima, que
	// nao deve ser confundida com dado faltando.
	CodigoDoMotivo *uint32 `protobuf:"varint,3,opt,name=codigo_do_motivo,json=codigoDoMotivo,proto3,oneof" json:"codigo_do_motivo,omitempty"`
	// Identificador de cracha AFIRMADO, capturado pelo leitor da origem.
	//
	// A origem NAO valida o cracha: durante a autonomia de buffer nao ha a quem
	// perguntar, e guardar credenciais em cada origem multiplicaria a superficie de
	// ataque pela frota inteira.
	//
	// O gateway resolve para a pessoa e guarda os dois valores separados. Cracha
	// nao reconhecido vira anomalia auditavel, nao registro perdido.
	//
	// DADO PESSOAL: identifica um trabalhador. Acesso restrito no modelo de leitura.
	IdDoCrachaAfirmado *string `protobuf:"bytes,4,opt,name=id_do_cracha_afirmado,json=idDoCrachaAfirmado,proto3,oneof" json:"id_do_cracha_afirmado,omitempty"`
	// Identificador de lote AFIRMADO, quando o operador o informa.
	//
	// A associacao autoritativa entre medicao e lote e DERIVADA no gateway, a
	// partir do registro de qual lote rodou em qual linha e quando — porque assim
	// ela e recomputavel se o registro do lote for corrigido. Este campo cobre o
	// caso em que so o operador sabe.
	IdDoLoteAfirmado *string `protobuf:"bytes,5,opt,name=id_do_lote_afirmado,json=idDoLoteAfirmado,proto3,oneof" json:"id_do_lote_afirmado,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MudancaDeEstadoDeMaquina) Reset() {
	*x = MudancaDeEstadoDeMaquina{}
	mi := &file_synkacore_contrato_v1_aquisicao_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MudancaDeEstadoDeMaquina) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MudancaDeEstadoDeMaquina) ProtoMessage() {}

func (x *MudancaDeEstadoDeMaquina) ProtoReflect() protoreflect.Message {
	mi := &file_synkacore_contrato_v1_aquisicao_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MudancaDeEstadoDeMaquina.ProtoReflect.Descriptor instead.
func (*MudancaDeEstadoDeMaquina) Descriptor() ([]byte, []int) {
	return file_synkacore_contrato_v1_aquisicao_proto_rawDescGZIP(), []int{8}
}

func (x *MudancaDeEstadoDeMaquina) GetEndereco() *EnderecoDeCanal {
	if x != nil {
		return x.Endereco
	}
	return nil
}

func (x *MudancaDeEstadoDeMaquina) GetEstado() EstadoDeMaquina {
	if x != nil && x.Estado != nil {
		return *x.Estado
	}
	return EstadoDeMaquina_ESTADO_DE_MAQUINA_NAO_ESPECIFICADO
}

func (x *MudancaDeEstadoDeMaquina) GetCodigoDoMotivo() uint32 {
	if x != nil && x.CodigoDoMotivo != nil {
		return *x.CodigoDoMotivo
	}
	return 0
}

func (x *MudancaDeEstadoDeMaquina) GetIdDoCrachaAfirmado() string {
	if x != nil && x.IdDoCrachaAfirmado != nil {
		return *x.IdDoCrachaAfirmado
	}
	return ""
}

func (x *MudancaDeEstadoDeMaquina) GetIdDoLoteAfirmado() string {
	if x != nil && x.IdDoLoteAfirmado != nil {
		return *x.IdDoLoteAfirmado
	}
	return ""
}

// SaudeDaOrigem e a telemetria interna de quem produz o dado.
type SaudeDaOrigem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Os DOIS campos de memoria sao obrigatorios e viajam SEPARADOS.
	//
	// "Escopo enxuto da imunidade a vazamento de memoria" e afirmacao falsa: quem
	// aloca numa origem embarcada nao e a logica de negocio, e a infraestrutura —
	// handshake TLS, serializacao e sobretudo o ciclo de reconexao de rede.
	//
	// E o risco real nem e o vazamento classico, e a FRAGMENTACAO: o total livre
	// continua alto enquanto o maior bloco contiguo encolhe, ate a proxima
	// alocacao de TLS falhar, tipicamente depois de dias ou semanas.
	//
	//	memoria livre alta + maior bloco baixo == fragmentacao avancada
	//
	// So o primeiro campo esconderia exatamente a falha que mata a origem em campo.
	BytesLivresDeMemoria   *uint32 `protobuf:"varint,1,opt,name=bytes_livres_de_memoria,json=bytesLivresDeMemoria,proto3,oneof" json:"bytes_livres_de_memoria,omitempty"`
	MaiorBlocoLivreEmBytes *uint32 `protobuf:"varint,2,opt,name=maior_bloco_livre_em_bytes,json=maiorBlocoLivreEmBytes,proto3,oneof" json:"maior_bloco_livre_em_bytes,omitempty"`
	// Distingue perda por rede de perda por defeito da origem.
	SinalDeRadioDbm *int32 `protobuf:"varint,3,opt,name=sinal_de_radio_dbm,json=sinalDeRadioDbm,proto3,oneof" json:"sinal_de_radio_dbm,omitempty"`
	// Denuncia reinicio em laco, que o watchdog mascara com sucesso aparente: a
	// origem responde, mas nunca fica de pe tempo suficiente para servir.
	ContagemDeReinicios *uint32 `protobuf:"varint,4,opt,name=contagem_de_reinicios,json=contagemDeReinicios,proto3,oneof" json:"contagem_de_reinicios,omitempty"`
	// Contabilidade da politica de saturacao. Perda aceita continua sendo perda
	// CONHECIDA, em numeros.
	RegistrosDescartados *uint32 `protobuf:"varint,5,opt,name=registros_descartados,json=registrosDescartados,proto3,oneof" json:"registros_descartados,omitempty"`
	// Ocupacao atual do buffer local. Permite alarmar ANTES de saturar.
	BytesUsadosNoBuffer *uint32 `protobuf:"varint,6,opt,name=bytes_usados_no_buffer,json=bytesUsadosNoBuffer,proto3,oneof" json:"bytes_usados_no_buffer,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SaudeDaOrigem) Reset() {
	*x = SaudeDaOrigem{}
	mi := &file_synkacore_contrato_v1_aquisicao_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaudeDaOrigem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaudeDaOrigem) ProtoMessage() {}

func (x *SaudeDaOrigem) ProtoReflect() protoreflect.Message {
	mi := &file_synkacore_contrato_v1_aquisicao_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaudeDaOrigem.ProtoReflect.Descriptor instead.
func (*SaudeDaOrigem) Descriptor() ([]byte, []int) {
	return file_synkacore_contrato_v1_aquisicao_proto_rawDescGZIP(), []int{9}
}

func (x *SaudeDaOrigem) GetBytesLivresDeMemoria() uint32 {
	if x != nil && x.BytesLivresDeMemoria != nil {
		return *x.BytesLivresDeMemoria
	}
	return 0
}

func (x *SaudeDaOrigem) GetMaiorBlocoLivreEmBytes() uint32 {
	if x != nil && x.MaiorBlocoLivreEmBytes != nil {
		return *x.MaiorBlocoLivreEmBytes
	}
	return 0
}

func (x *SaudeDaOrigem) GetSinalDeRadioDbm() int32 {
	if x != nil && x.SinalDeRadioDbm != nil {
		return *x.SinalDeRadioDbm
	}
	return 0
}

func (x *SaudeDaOrigem) GetContagemDeReinicios() uint32 {
	if x != nil && x.ContagemDeReinicios != nil {
		return *x.ContagemDeReinicios
	}
	return 0
}

func (x *SaudeDaOrigem) GetRegistrosDescartados() uint32 {
	if x != nil && x.RegistrosDescartados != nil {
		return *x.RegistrosDescartados
	}
	return 0
}

func (x *SaudeDaOrigem) GetBytesUsadosNoBuffer() uint32 {
	if x != nil && x.BytesUsadosNoBuffer != nil {
		return *x.BytesUsadosNoBuffer
	}
	return 0
}

// LacunaDeBuffer admite explicitamente que houve descarte.
//
// Existe para que perda nunca seja silenciosa: em vez de um buraco invisivel num
// relatorio, a lacuna vira um fato VISIVEL no dado, com intervalo e contagem. E a
// diferenca pratica entre um sistema que mente e um que admite o que nao sabe.
type LacunaDeBuffer struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	RegistrosPerdidos        *uint64                `protobuf:"varint,1,opt,name=registros_perdidos,json=registrosPerdidos,proto3,oneof" json:"registros_perdidos,omitempty"`
	PrimeiraSequenciaPerdida *uint64                `protobuf:"varint,2,opt,name=primeira_sequencia_perdida,json=primeiraSequenciaPerdida,proto3,oneof" json:"primeira_sequencia_perdida,omitempty"`
	UltimaSequenciaPerdida   *uint64                `protobuf:"varint,3,opt,name=ultima_sequencia_perdida,json=ultimaSequenciaPerdida,proto3,oneof" json:"ultima_sequencia_perdida,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *LacunaDeBuffer) Reset() {
	*x = LacunaDeBuffer{}
	mi := &file_synkacore_contrato_v1_aquisicao_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LacunaDeBuffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LacunaDeBuffer) ProtoMessage() {}

func (x *LacunaDeBuffer) ProtoReflect() protoreflect.Message {
	mi := &file_synkacore_contrato_v1_aquisicao_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LacunaDeBuffer.ProtoReflect.Descriptor instead.
func (*LacunaDeBuffer) Descriptor() ([]byte, []int) {
	return file_synkacore_contrato_v1_aquisicao_proto_rawDescGZIP(), []int{10}
}

func (x *LacunaDeBuffer) GetRegistrosPerdidos() uint64 {
	if x != nil && x.RegistrosPerdidos != nil {
		return *x.RegistrosPerdidos
	}
	return 0
}

func (x *LacunaDeBuffer) GetPrimeiraSequenciaPerdida() uint64 {
	if x != nil && x.PrimeiraSequenciaPerdida != nil {
		return *x.PrimeiraSequenciaPerdida
	}
	return 0
}

func (x *LacunaDeBuffer) GetUltimaSequenciaPerdida() uint64 {
	if x != nil && x.UltimaSequenciaPerdida != nil {
		return *x.UltimaSequenciaPerdida
	}
	return 0
}

// DescritorDaOrigem declara o que esta origem e e o que cada canal mede.
//
// Enviado no boot e periodicamente. Baixa frequencia de proposito: assim a
// descricao do canal NAO precisa viajar em cada amostra, o que economiza a maior
// parte dos bytes do sistema.
//
// Serve de rede de protecao de comissionamento: o gateway compara o que a origem
// acredita medir com o mapeamento que ele mesmo tem, e denuncia divergencia —
// canal trocado no painel deixa de ser erro silencioso.
type DescritorDaOrigem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	VersaoDoFirmware *string                `protobuf:"bytes,1,opt,name=versao_do_firmware,json=versaoDoFirmware,proto3,oneof" json:"versao_do_firmware,omitempty"`
	ModeloDoHardware *string                `protobuf:"bytes,2,opt,name=modelo_do_hardware,json=modeloDoHardware,proto3,oneof" json:"modelo_do_hardware,omitempty"`
	Canais           []*DescritorDeCanal    `protobuf:"bytes,3,rep,name=canais,proto3" json:"canais,omitempty"`
	// Versao do catalogo de motivos de parada carregada nesta origem.
	//
	// Permite ao gateway detectar deriva: se a origem exibe rotulos de uma versao
	// antiga, os codigos que ela envia podem significar outra coisa. Toda
	// configuracao replicada na origem declara sua versao, e o gateway confere.
	VersaoDoCatalogoDeMotivos *uint32 `protobuf:"varint,4,opt,name=versao_do_catalogo_de_motivos,json=versaoDoCatalogoDeMotivos,proto3,oneof" json:"versao_do_catalogo_de_motivos,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *DescritorDaOrigem) Reset() {
	*x = DescritorDaOrigem{}
	mi := &file_synkacore_contrato_v1_aquisicao_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescritorDaOrigem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescritorDaOrigem) ProtoMessage() {}

func (x *DescritorDaOrigem) ProtoReflect() protoreflect.Message {
	mi := &file_synkacore_contrato_v1_aquisicao_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescritorDaOrigem.ProtoReflect.Descriptor instead.
func (*DescritorDaOrigem) Descriptor() ([]byte, []int) {
	return file_synkacore_contrato_v1_aquisicao_proto_rawDescGZIP(), []int{11}
}

func (x *DescritorDaOrigem) GetVersaoDoFirmware() string {
	if x != nil && x.VersaoDoFirmware != nil {
		return *x.VersaoDoFirmware
	}
	return ""
}

func (x *DescritorDaOrigem) GetModeloDoHardware() string {
	if x != nil && x.ModeloDoHardware != nil {
		return *x.ModeloDoHardware
	}
	return ""
}

func (x *DescritorDaOrigem) GetCanais() []*DescritorDeCanal {
	if x != nil {
		return x.Canais
	}
	return nil
}

func (x *DescritorDaOrigem) GetVersaoDoCatalogoDeMotivos() uint32 {
	if x != nil && x.VersaoDoCatalogoDeMotivos != nil {
		return *x.VersaoDoCatalogoDeMotivos
	}
	return 0
}

type DescritorDeCanal struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Endereco *EnderecoDeCanal       `protobuf:"bytes,1,opt,name=endereco,proto3,oneof" json:"endereco,omitempty"`
	// O que a origem ACREDITA medir. Autoritativo e o mapeamento do gateway; este
	// valor existe para detectar discordancia entre os dois.
	Grandeza *Grandeza `protobuf:"varint,2,opt,name=grandeza,proto3,enum=synkacore.contrato.v1.Grandeza,oneof" json:"grandeza,omitempty"`
	// Unidade em notacao UCUM (por exemplo: "Cel", "kPa", "L/min", "kg").
	Unidade *string `protobuf:"bytes,3,opt,name=unidade,proto3,oneof" json:"unidade,omitempty"`
	// Periodo nominal de amostragem, para o gateway saber o que esperar e alarmar
	// quando um canal fica mudo.
	PeriodoDeAmostragemMs *uint32 `protobuf:"varint,4,opt,name=periodo_de_amostragem_ms,json=periodoDeAmostragemMs,proto3,oneof" json:"periodo_de_amostragem_ms,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DescritorDeCanal) Reset() {
	*x = DescritorDeCanal{}
	mi := &file_synkacore_contrato_v1_aquisicao_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescritorDeCanal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescritorDeCanal) ProtoMessage() {}

func (x *DescritorDeCanal) ProtoReflect() protoreflect.Message {
	mi := &file_synkacore_contrato_v1_aquisicao_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescritorDeCanal.ProtoReflect.Descriptor instead.
func (*DescritorDeCanal) Descriptor() ([]byte, []int) {
	return file_synkacore_contrato_v1_aquisicao_proto_rawDescGZIP(), []int{12}
}

func (x *DescritorDeCanal) GetEndereco() *EnderecoDeCanal {
	if x != nil {
		return x.Endereco
	}
	return nil
}

func (x *DescritorDeCanal) GetGrandeza() Grandeza {
	if x != nil && x.Grandeza != nil {
		return *x.Grandeza
	}
	return Grandeza_GRANDEZA_NAO_ESPECIFICADO
}

func (x *DescritorDeCanal) GetUnidade() string {
	if x != nil && x.Unidade != nil {
		return *x.Unidade
	}
	return ""
}

func (x *DescritorDeCanal) GetPeriodoDeAmostragemMs() uint32 {
	if x != nil && x.PeriodoDeAmostragemMs != nil {
		return *x.PeriodoDeAmostragemMs
	}
	return 0
}

var file_synkacore_contrato_v1_aquisicao_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*ClasseDeDado)(nil),
		Field:         50001,
		Name:          "synkacore.contrato.v1.classe_de_dado",
		Tag:           "varint,50001,opt,name=classe_de_dado,enum=synkacore.contrato.v1.ClasseDeDado",
		Filename:      "synkacore/contrato/v1/aquisicao.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// Anota o tipo de conteudo com sua classe de dado.
	//
	// optional synkacore.contrato.v1.ClasseDeDado classe_de_dado = 50001;
	E_ClasseDeDado = &file_synkacore_contrato_v1_aquisicao_proto_extTypes[0]
)

var File_synkacore_contrato_v1_aquisicao_proto protoreflect.FileDescriptor

const file_synkacore_contrato_v1_aquisicao_proto_rawDesc = "" +
	"\n" +
	"%synkacore/contrato/v1/aquisicao.proto\x12\x15synkacore.contrato.v1\x1a google/protobuf/descriptor.proto\"\xe8\x02\n" +
	"\aRemessa\x12/\n" +
	"\x11versao_do_esquema\x18\x01 \x01(\rH\x00R\x0fversaoDoEsquema\x88\x01\x01\x12-\n" +
	"\x10id_da_instalacao\x18\x02 \x01(\tH\x01R\x0eidDaInstalacao\x88\x01\x01\x12/\n" +
	"\x11id_do_dispositivo\x18\x03 \x01(\tH\x02R\x0fidDoDispositivo\x88\x01\x01\x123\n" +
	"\x14id_da_sessao_de_boot\x18\x04 \x01(\tH\x03R\x10idDaSessaoDeBoot\x88\x01\x01\x12=\n" +
	"\tenvelopes\x18\x05 \x03(\v2\x1f.synkacore.contrato.v1.EnvelopeR\tenvelopesB\x14\n" +
	"\x12_versao_do_esquemaB\x13\n" +
	"\x11_id_da_instalacaoB\x14\n" +
	"\x12_id_do_dispositivoB\x17\n" +
	"\x15_id_da_sessao_de_boot\"\xf1\x06\n" +
	"\bEnvelope\x123\n" +
	"\x13numero_de_sequencia\x18\x01 \x01(\x04H\x01R\x11numeroDeSequencia\x88\x01\x01\x12+\n" +
	"\x0ftempo_ligado_ms\x18\x02 \x01(\x04H\x02R\rtempoLigadoMs\x88\x01\x01\x12P\n" +
	"\x0famostra_escalar\x18\x03 \x01(\v2%.synkacore.contrato.v1.AmostraEscalarH\x00R\x0eamostraEscalar\x12Z\n" +
	"\x13leitura_de_contador\x18\x04 \x01(\v2(.synkacore.contrato.v1.LeituraDeContadorH\x00R\x11leituraDeContador\x12V\n" +
	"\x11transicao_digital\x18\x05 \x01(\v2'.synkacore.contrato.v1.TransicaoDigitalH\x00R\x10transicaoDigital\x12S\n" +
	"\x10amostra_agregada\x18\x06 \x01(\v2&.synkacore.contrato.v1.AmostraAgregadaH\x00R\x0famostraAgregada\x12q\n" +
	"\x1cmudanca_de_estado_de_maquina\x18\a \x01(\v2/.synkacore.contrato.v1.MudancaDeEstadoDeMaquinaH\x00R\x18mudancaDeEstadoDeMaquina\x12N\n" +
	"\x0fsaude_da_origem\x18\b \x01(\v2$.synkacore.contrato.v1.SaudeDaOrigemH\x00R\rsaudeDaOrigem\x12Q\n" +
	"\x10lacuna_de_buffer\x18\t \x01(\v2%.synkacore.contrato.v1.LacunaDeBufferH\x00R\x0elacunaDeBuffer\x12Z\n" +
	"\x13descritor_da_origem\x18\n" +
	" \x01(\v2(.synkacore.contrato.v1.DescritorDaOrigemH\x00R\x11descritorDaOrigemB\n" +
	"\n" +
	"\bconteudoB\x16\n" +
	"\x14_numero_de_sequenciaB\x12\n" +
	"\x10_tempo_ligado_ms\"\x83\x02\n" +
	"\x14ConfirmacaoDeRemessa\x12:\n" +
	"\x17duravel_ate_a_sequencia\x18\x01 \x01(\x04H\x00R\x14duravelAteASequencia\x88\x01\x01\x12R\n" +
	"%sequencias_rejeitadas_definitivamente\x18\x02 \x03(\x04R#sequenciasRejeitadasDefinitivamente\x12+\n" +
	"\x0frepetir_apos_ms\x18\x03 \x01(\rH\x01R\rrepetirAposMs\x88\x01\x01B\x1a\n" +
	"\x18_duravel_ate_a_sequenciaB\x12\n" +
	"\x10_repetir_apos_ms\"\x96\x01\n" +
	"\x0fEnderecoDeCanal\x12-\n" +
	"\x10indice_do_modulo\x18\x01 \x01(\rH\x00R\x0eindiceDoModulo\x88\x01\x01\x12+\n" +
	"\x0findice_do_canal\x18\x02 \x01(\rH\x01R\rindiceDoCanal\x88\x01\x01B\x13\n" +
	"\x11_indice_do_moduloB\x12\n" +
	"\x10_indice_do_canal\"\x91\x01\n" +
	"\x0eAmostraEscalar\x12G\n" +
	"\bendereco\x18\x01 \x01(\v2&.synkacore.contrato.v1.EnderecoDeCanalH\x00R\bendereco\x88\x01\x01\x12\x19\n" +
	"\x05valor\x18\x02 \x01(\x02H\x01R\x05valor\x88\x01\x01:\x04\x88\xb5\x18\x01B\v\n" +
	"\t_enderecoB\b\n" +
	"\x06_valor\"\xa1\x03\n" +
	"\x0fAmostraAgregada\x12G\n" +
	"\bendereco\x18\x01 \x01(\v2&.synkacore.contrato.v1.EnderecoDeCanalH\x00R\bendereco\x88\x01\x01\x12 \n" +
	"\tjanela_ms\x18\x02 \x01(\rH\x01R\bjanelaMs\x88\x01\x01\x129\n" +
	"\x16quantidade_de_amostras\x18\x03 \x01(\rH\x02R\x14quantidadeDeAmostras\x88\x01\x01\x12\x1b\n" +
	"\x06minimo\x18\x04 \x01(\x02H\x03R\x06minimo\x88\x01\x01\x12\x1b\n" +
	"\x06maximo\x18\x05 \x01(\x02H\x04R\x06maximo\x88\x01\x01\x12\x19\n" +
	"\x05media\x18\x06 \x01(\x02H\x05R\x05media\x88\x01\x01\x12&\n" +
	"\fvalor_eficaz\x18\a \x01(\x02H\x06R\vvalorEficaz\x88\x01\x01:\x04\x88\xb5\x18\x01B\v\n" +
	"\t_enderecoB\f\n" +
	"\n" +
	"_janela_msB\x19\n" +
	"\x17_quantidade_de_amostrasB\t\n" +
	"\a_minimoB\t\n" +
	"\a_maximoB\b\n" +
	"\x06_mediaB\x0f\n" +
	"\r_valor_eficaz\"\xba\x01\n" +
	"\x11LeituraDeContador\x12G\n" +
	"\bendereco\x18\x01 \x01(\v2&.synkacore.contrato.v1.EnderecoDeCanalH\x00R\bendereco\x88\x01\x01\x122\n" +
	"\x12contagem_acumulada\x18\x02 \x01(\x04H\x01R\x11contagemAcumulada\x88\x01\x01:\x04\x88\xb5\x18\x02B\v\n" +
	"\t_enderecoB\x15\n" +
	"\x13_contagem_acumulada\"\x93\x01\n" +
	"\x10TransicaoDigital\x12G\n" +
	"\bendereco\x18\x01 \x01(\v2&.synkacore.contrato.v1.EnderecoDeCanalH\x00R\bendereco\x88\x01\x01\x12\x19\n" +
	"\x05ativo\x18\x02 \x01(\bH\x01R\x05ativo\x88\x01\x01:\x04\x88\xb5\x18\x02B\v\n" +
	"\t_enderecoB\b\n" +
	"\x06_ativo\"\xa8\x03\n" +
	"\x18MudancaDeEstadoDeMaquina\x12G\n" +
	"\bendereco\x18\x01 \x01(\v2&.synkacore.contrato.v1.EnderecoDeCanalH\x00R\bendereco\x88\x01\x01\x12C\n" +
	"\x06estado\x18\x02 \x01(\x0e2&.synkacore.contrato.v1.EstadoDeMaquinaH\x01R\x06estado\x88\x01\x01\x12-\n" +
	"\x10codigo_do_motivo\x18\x03 \x01(\rH\x02R\x0ecodigoDoMotivo\x88\x01\x01\x126\n" +
	"\x15id_do_cracha_afirmado\x18\x04 \x01(\tH\x03R\x12idDoCrachaAfirmado\x88\x01\x01\x122\n" +
	"\x13id_do_lote_afirmado\x18\x05 \x01(\tH\x04R\x10idDoLoteAfirmado\x88\x01\x01:\x04\x88\xb5\x18\x02B\v\n" +
	"\t_enderecoB\t\n" +
	"\a_estadoB\x13\n" +
	"\x11_codigo_do_motivoB\x18\n" +
	"\x16_id_do_cracha_afirmadoB\x16\n" +
	"\x14_id_do_lote_afirmado\"\x92\x04\n" +
	"\rSaudeDaOrigem\x12:\n" +
	"\x17bytes_livres_de_memoria\x18\x01 \x01(\rH\x00R\x14bytesLivresDeMemoria\x88\x01\x01\x12?\n" +
	"\x1amaior_bloco_livre_em_bytes\x18\x02 \x01(\rH\x01R\x16maiorBlocoLivreEmBytes\x88\x01\x01\x120\n" +
	"\x12sinal_de_radio_dbm\x18\x03 \x01(\x05H\x02R\x0fsinalDeRadioDbm\x88\x01\x01\x127\n" +
	"\x15contagem_de_reinicios\x18\x04 \x01(\rH\x03R\x13contagemDeReinicios\x88\x01\x01\x128\n" +
	"\x15registros_descartados\x18\x05 \x01(\rH\x04R\x14registrosDescartados\x88\x01\x01\x128\n" +
	"\x16bytes_usados_no_buffer\x18\x06 \x01(\rH\x05R\x13bytesUsadosNoBuffer\x88\x01\x01:\x04\x88\xb5\x18\x01B\x1a\n" +
	"\x18_bytes_livres_de_memoriaB\x1d\n" +
	"\x1b_maior_bloco_livre_em_bytesB\x15\n" +
	"\x13_sinal_de_radio_dbmB\x18\n" +
	"\x16_contagem_de_reiniciosB\x18\n" +
	"\x16_registros_descartadosB\x19\n" +
	"\x17_bytes_usados_no_buffer\"\x9f\x02\n" +
	"\x0eLacunaDeBuffer\x122\n" +
	"\x12registros_perdidos\x18\x01 \x01(\x04H\x00R\x11registrosPerdidos\x88\x01\x01\x12A\n" +
	"\x1aprimeira_sequencia_perdida\x18\x02 \x01(\x04H\x01R\x18primeiraSequenciaPerdida\x88\x01\x01\x12=\n" +
	"\x18ultima_sequencia_perdida\x18\x03 \x01(\x04H\x02R\x16ultimaSequenciaPerdida\x88\x01\x01:\x04\x88\xb5\x18\x02B\x15\n" +
	"\x13_registros_perdidosB\x1d\n" +
	"\x1b_primeira_sequencia_perdidaB\x1b\n" +
	"\x19_ultima_sequencia_perdida\"\xd7\x02\n" +
	"\x11DescritorDaOrigem\x121\n" +
	"\x12versao_do_firmware\x18\x01 \x01(\tH\x00R\x10versaoDoFirmware\x88\x01\x01\x121\n" +
	"\x12modelo_do_hardware\x18\x02 \x01(\tH\x01R\x10modeloDoHardware\x88\x01\x01\x12?\n" +
	"\x06canais\x18\x03 \x03(\v2'.synkacore.contrato.v1.DescritorDeCanalR\x06canais\x12E\n" +
	"\x1dversao_do_catalogo_de_motivos\x18\x04 \x01(\rH\x02R\x19versaoDoCatalogoDeMotivos\x88\x01\x01:\x04\x88\xb5\x18\x01B\x15\n" +
	"\x13_versao_do_firmwareB\x15\n" +
	"\x13_modelo_do_hardwareB \n" +
	"\x1e_versao_do_catalogo_de_motivos\"\xbd\x02\n" +
	"\x10DescritorDeCanal\x12G\n" +
	"\bendereco\x18\x01 \x01(\v2&.synkacore.contrato.v1.EnderecoDeCanalH\x00R\bendereco\x88\x01\x01\x12@\n" +
	"\bgrandeza\x18\x02 \x01(\x0e2\x1f.synkacore.contrato.v1.GrandezaH\x01R\bgrandeza\x88\x01\x01\x12\x1d\n" +
	"\aunidade\x18\x03 \x01(\tH\x02R\aunidade\x88\x01\x01\x12<\n" +
	"\x18periodo_de_amostragem_ms\x18\x04 \x01(\rH\x03R\x15periodoDeAmostragemMs\x88\x01\x01B\v\n" +
	"\t_enderecoB\v\n" +
	"\t_grandezaB\n" +
	"\n" +
	"\b_unidadeB\x1b\n" +
	"\x19_periodo_de_amostragem_ms*s\n" +
	"\fClasseDeDado\x12#\n" +
	"\x1fCLASSE_DE_DADO_NAO_ESPECIFICADO\x10\x00\x12\x1a\n" +
	"\x16CLASSE_DE_DADO_AMOSTRA\x10\x01\x12\"\n" +
	"\x1eCLASSE_DE_DADO_EVENTO_DISCRETO\x10\x02*\xfc\x01\n" +
	"\x0fEstadoDeMaquina\x12&\n" +
	"\"ESTADO_DE_MAQUINA_NAO_ESPECIFICADO\x10\x00\x12\x1d\n" +
	"\x19ESTADO_DE_MAQUINA_RODANDO\x10\x01\x12\x1c\n" +
	"\x18ESTADO_DE_MAQUINA_PARADA\x10\x02\x12\x1b\n" +
	"\x17ESTADO_DE_MAQUINA_SETUP\x10\x03\x12\x1c\n" +
	"\x18ESTADO_DE_MAQUINA_OCIOSA\x10\x04\x12+\n" +
	"'ESTADO_DE_MAQUINA_MANUTENCAO_PROGRAMADA\x10\x05\x12\x1c\n" +
	"\x18ESTADO_DE_MAQUINA_QUEBRA\x10\x06*\xb6\x04\n" +
	"\bGrandeza\x12\x1d\n" +
	"\x19GRANDEZA_NAO_ESPECIFICADO\x10\x00\x12\x18\n" +
	"\x14GRANDEZA_TEMPERATURA\x10\x01\x12\x14\n" +
	"\x10GRANDEZA_PRESSAO\x10\x02\x12\x1a\n" +
	"\x16GRANDEZA_UMIDADE_DO_AR\x10\x03\x12\x12\n" +
	"\x0eGRANDEZA_VAZAO\x10\x04\x12\x12\n" +
	"\x0eGRANDEZA_MASSA\x10\x05\x12\x12\n" +
	"\x0eGRANDEZA_NIVEL\x10\x06\x12\x1e\n" +
	"\x1aGRANDEZA_CORRENTE_ELETRICA\x10\a\x12#\n" +
	"\x1fGRANDEZA_ACELERACAO_DE_VIBRACAO\x10\b\x12\x1b\n" +
	"\x17GRANDEZA_ESTADO_DIGITAL\x10\t\x12\x1e\n" +
	"\x1aGRANDEZA_CONTAGEM_DE_PECAS\x10\n" +
	"\x12\x0f\n" +
	"\vGRANDEZA_PH\x10\v\x12#\n" +
	"\x1fGRANDEZA_CONDUTIVIDADE_ELETRICA\x10\f\x12\x1c\n" +
	"\x18GRANDEZA_UMIDADE_DE_GRAO\x10\r\x12\x11\n" +
	"\rGRANDEZA_BRIX\x10\x0e\x12\x14\n" +
	"\x10GRANDEZA_ROTACAO\x10\x0f\x12\x13\n" +
	"\x0fGRANDEZA_TORQUE\x10\x10\x12\x1e\n" +
	"\x1aGRANDEZA_VELOCIDADE_LINEAR\x10\x11\x12\x13\n" +
	"\x0fGRANDEZA_TENSAO\x10\x12\x12\x1b\n" +
	"\x17GRANDEZA_POTENCIA_ATIVA\x10\x13\x12\x1d\n" +
	"\x19GRANDEZA_ENERGIA_ELETRICA\x10\x14:o\n" +
	"\x0eclasse_de_dado\x12\x1f.google.protobuf.MessageOptions\x18ц\x03 \x01(\x0e2#.synkacore.contrato.v1.ClasseDeDadoR\fclasseDeDado\x88\x01\x01BBZ@github.com/ViktorWalde/SynkaCore/internal/contrato/v1;contratov1b\x06proto3"

var (
	file_synkacore_contrato_v1_aquisicao_proto_rawDescOnce sync.Once
	file_synkacore_contrato_v1_aquisicao_proto_rawDescData []byte
)

func file_synkacore_contrato_v1_aquisicao_proto_rawDescGZIP() []byte {
	file_synkacore_contrato_v1_aquisicao_proto_rawDescOnce.Do(func() {
		file_synkacore_contrato_v1_aquisicao_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_synkacore_contrato_v1_aquisicao_proto_rawDesc), len(file_synkacore_contrato_v1_aquisicao_proto_rawDesc)))
	})
	return file_synkacore_contrato_v1_aquisicao_proto_rawDescData
}

var file_synkacore_contrato_v1_aquisicao_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_synkacore_contrato_v1_aquisicao_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_synkacore_contrato_v1_aquisicao_proto_goTypes = []any{
	(ClasseDeDado)(0),                   // 0: synkacore.contrato.v1.ClasseDeDado
	(EstadoDeMaquina)(0),                // 1: synkacore.contrato.v1.EstadoDeMaquina
	(Grandeza)(0),                       // 2: synkacore.contrato.v1.Grandeza
	(*Remessa)(nil),                     // 3: synkacore.contrato.v1.Remessa
	(*Envelope)(nil),                    // 4: synkacore.contrato.v1.Envelope
	(*ConfirmacaoDeRemessa)(nil),        // 5: synkacore.contrato.v1.ConfirmacaoDeRemessa
	(*EnderecoDeCanal)(nil),             // 6: synkacore.contrato.v1.EnderecoDeCanal
	(*AmostraEscalar)(nil),              // 7: synkacore.contrato.v1.AmostraEscalar
	(*AmostraAgregada)(nil),             // 8: synkacore.contrato.v1.AmostraAgregada
	(*LeituraDeContador)(nil),           // 9: synkacore.contrato.v1.LeituraDeContador
	(*TransicaoDigital)(nil),            // 10: synkacore.contrato.v1.TransicaoDigital
	(*MudancaDeEstadoDeMaquina)(nil),    // 11: synkacore.contrato.v1.MudancaDeEstadoDeMaquina
	(*SaudeDaOrigem)(nil),               // 12: synkacore.contrato.v1.SaudeDaOrigem
	(*LacunaDeBuffer)(nil),              // 13: synkacore.contrato.v1.LacunaDeBuffer
	(*DescritorDaOrigem)(nil),           // 14: synkacore.contrato.v1.DescritorDaOrigem
	(*DescritorDeCanal)(nil),            // 15: synkacore.contrato.v1.DescritorDeCanal
	(*descriptorpb.MessageOptions)(nil), // 16: google.protobuf.MessageOptions
}
var file_synkacore_contrato_v1_aquisicao_proto_depIdxs = []int32{
	4,  // 0: synkacore.contrato.v1.Remessa.envelopes:type_name -> synkacore.contrato.v1.Envelope
	7,  // 1: synkacore.contrato.v1.Envelope.amostra_escalar:type_name -> synkacore.contrato.v1.AmostraEscalar
	9,  // 2: synkacore.contrato.v1.Envelope.leitura_de_contador:type_name -> synkacore.contrato.v1.LeituraDeContador
	10, // 3: synkacore.contrato.v1.Envelope.transicao_digital:type_name -> synkacore.contrato.v1.TransicaoDigital
	8,  // 4: synkacore.contrato.v1.Envelope.amostra_agregada:type_name -> synkacore.contrato.v1.AmostraAgregada
	11, // 5: synkacore.contrato.v1.Envelope.mudanca_de_estado_de_maquina:type_name -> synkacore.contrato.v1.MudancaDeEstadoDeMaquina
	12, // 6: synkacore.contrato.v1.Envelope.saude_da_origem:type_name -> synkacore.contrato.v1.SaudeDaOrigem
	13, // 7: synkacore.contrato.v1.Envelope.lacuna_de_buffer:type_name -> synkacore.contrato.v1.LacunaDeBuffer
	14, // 8: synkacore.contrato.v1.Envelope.descritor_da_origem:type_name -> synkacore.contrato.v1.DescritorDaOrigem
	6,  // 9: synkacore.contrato.v1.AmostraEscalar.endereco:type_name -> synkacore.contrato.v1.EnderecoDeCanal
	6,  // 10: synkacore.contrato.v1.AmostraAgregada.endereco:type_name -> synkacore.contrato.v1.EnderecoDeCanal
	6,  // 11: synkacore.contrato.v1.LeituraDeContador.endereco:type_name -> synkacore.contrato.v1.EnderecoDeCanal
	6,  // 12: synkacore.contrato.v1.TransicaoDigital.endereco:type_name -> synkacore.contrato.v1.EnderecoDeCanal
	6,  // 13: synkacore.contrato.v1.MudancaDeEstadoDeMaquina.endereco:type_name -> synkacore.contrato.v1.EnderecoDeCanal
	1,  // 14: synkacore.contrato.v1.MudancaDeEstadoDeMaquina.estado:type_name -> synkacore.contrato.v1.EstadoDeMaquina
	15, // 15: synkacore.contrato.v1.DescritorDaOrigem.canais:type_name -> synkacore.contrato.v1.DescritorDeCanal
	6,  // 16: synkacore.contrato.v1.DescritorDeCanal.endereco:type_name -> synkacore.contrato.v1.EnderecoDeCanal
	2,  // 17: synkacore.contrato.v1.DescritorDeCanal.grandeza:type_name -> synkacore.contrato.v1.Grandeza
	16, // 18: synkacore.contrato.v1.classe_de_dado:extendee -> google.protobuf.MessageOptions
	0,  // 19: synkacore.contrato.v1.classe_de_dado:type_name -> synkacore.contrato.v1.ClasseDeDado
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	19, // [19:20] is the sub-list for extension type_name
	18, // [18:19] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_synkacore_contrato_v1_aquisicao_proto_init() }
func file_synkacore_contrato_v1_aquisicao_proto_init() {
	if File_synkacore_contrato_v1_aquisicao_proto != nil {
		return
	}
	file_synkacore_contrato_v1_aquisicao_proto_msgTypes[0].OneofWrappers = []any{}
	file_synkacore_contrato_v1_aquisicao_proto_msgTypes[1].OneofWrappers = []any{
		(*Envelope_AmostraEscalar)(nil),
		(*Envelope_LeituraDeContador)(nil),
		(*Envelope_TransicaoDigital)(nil),
		(*Envelope_AmostraAgregada)(nil),
		(*Envelope_MudancaDeEstadoDeMaquina)(nil),
		(*Envelope_SaudeDaOrigem)(nil),
		(*Envelope_LacunaDeBuffer)(nil),
		(*Envelope_DescritorDaOrigem)(nil),
	}
	file_synkacore_contrato_v1_aquisicao_proto_msgTypes[2].OneofWrappers = []any{}
	file_synkacore_contrato_v1_aquisicao_proto_msgTypes[3].OneofWrappers = []any{}
	file_synkacore_contrato_v1_aquisicao_proto_msgTypes[4].OneofWrappers = []any{}
	file_synkacore_contrato_v1_aquisicao_proto_msgTypes[5].OneofWrappers = []any{}
	file_synkacore_contrato_v1_aquisicao_proto_msgTypes[6].OneofWrappers = []any{}
	file_synkacore_contrato_v1_aquisicao_proto_msgTypes[7].OneofWrappers = []any{}
	file_synkacore_contrato_v1_aquisicao_proto_msgTypes[8].OneofWrappers = []any{}
	file_synkacore_contrato_v1_aquisicao_proto_msgTypes[9].OneofWrappers = []any{}
	file_synkacore_contrato_v1_aquisicao_proto_msgTypes[10].OneofWrappers = []any{}
	file_synkacore_contrato_v1_aquisicao_proto_msgTypes[11].OneofWrappers = []any{}
	file_synkacore_contrato_v1_aquisicao_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_synkacore_contrato_v1_aquisicao_proto_rawDesc), len(file_synkacore_contrato_v1_aquisicao_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_synkacore_contrato_v1_aquisicao_proto_goTypes,
		DependencyIndexes: file_synkacore_contrato_v1_aquisicao_proto_depIdxs,
		EnumInfos:         file_synkacore_contrato_v1_aquisicao_proto_enumTypes,
		MessageInfos:      file_synkacore_contrato_v1_aquisicao_proto_msgTypes,
		ExtensionInfos:    file_synkacore_contrato_v1_aquisicao_proto_extTypes,
	}.Build()
	File_synkacore_contrato_v1_aquisicao_proto = out.File
	file_synkacore_contrato_v1_aquisicao_proto_goTypes = nil
	file_synkacore_contrato_v1_aquisicao_proto_depIdxs = nil
}
